### ISSUE TITLE
[BUG]  Unable to build against aws-xray-sdk-go package

### ISSUE THREAD

**Issue by j-fulbright** [DataDog/orchestrion#458]
When attempting to build using orchestrion my package will not build due to this error: 

`github.com/aws/aws-xray-sdk-go@v1.8.5/xray/sql_context.go:62: driver.Driver is not a type`

This does not occur when building without the Orchestrion toolchain / package. 

Using latest version of Go, along with whatever is most recently pulled via the `go get -u and go mod tidy` process.

**Comment by eliottness** [comment]
👋 Thanks for bringing this up. We just released [`orchestrion@1.0.2`](https://github.com/DataDog/orchestrion/releases/tag/v1.0.2) to tag #449 fixing this.

**Comment by j-fulbright** [comment]
This still does not appear to be resolved. 

![Image](https://github.com/user-attachments/assets/0528c076-a504-4151-939d-65f628baafc1)
![Image](https://github.com/user-attachments/assets/1e63f2f9-58c0-41ac-adc9-46252c7f0ab4)

**Comment by RiverPhillips** [comment]
I'm still running into this error on v1.0.2. Could this please be reopened @eliottness
